# **What it does**: Checks that the code pushed passes all the required checks and generate sonar report.
# **Why we have it**: To make sure pushed code can only be merged when all the required checks passed.
# **Who does it impact**: App Service.
name: Check App Service

on:
  pull_request:
    branches:
      - staging
      - develop
      - main

env:
  ORG: knoldus Inc
  PROJECT_NAME: Sample-Project-name
  AUTHOR: Saumya (SaumyaBhushan)
jobs:
  check_sample_app_service:
    env:
      MODULE_NAME: sample-app-service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run test cases and generate reports for Sample-App-Service
        env:
          URL: "jdbc:h2:mem:test;MODE=Oracle;"
          DRIVER: "org.h2.Driver"
          USERNAME:
          PASSWORD:
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          echo "...........Compiling the code .........."
          sbt clean compile
      - name: check Scala format
        run : |
          echo "...........Checking Scalafmt ........"
          sbt scalafmtAll
      - name: check Scalstyle
        run: |
          echo "...........Checking Scalastyle ........"
          sbt scalastyle
      - name: check copy paste detector
        run: |
          echo "...........Checking copy paste detector ........"
          sbt cpd
      - name: check scapegoat
        run: |
          echo "...........Checking Scapegoat ..........."
          sbt scapegoat
      - name: check test coverage and create coverage report
        run: |
          echo "...........Checking Test Coverage and Coverage Report.........."
          sbt coverage test coverageReport
      - name: Sonar coverage report
        run: |
          echo ".............Sonar Coverage Report............."
          sbt sonarScan